"""
Django settings for bourgeois project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
import cx_Oracle

# cx_Oracle.init_oracle_client(lib_dir=r"C:\oracle18\instantclient_21_3") # 클라이언트 경로(windows)
# cx_Oracle.init_oracle_client(lib_dir=r"../pydata/bourgeois_Total/instantclient_21_3") # 클라이언트 경로(mac)
# cx_Oracle.init_oracle_client(lib_dir=r"/Users/uk/instantclient_19_8")
# cx_Oracle.init_oracle_client(lib_dir=r"/Users/hyeonchanglee/sw/instantclient_19_8") # 클라이언트 경로(lee_mac)
cx_Oracle.init_oracle_client(lib_dir=r"/Users/hyeonchanglee/sw/my_instantclient_19_8") # 클라이언트 경로(lee_mac)



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nd&bxcmeezvrqi%i^g2f+2ss@+@fvjsk*p^=*z75(ru0f!i-t+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'qnaboard',
    'adminpage',
    'membership',
    'analytics',
    'navertrend',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bourgeois.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bourgeois.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        #sqlite3
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        
        # #oracle windows
        # 'ENGINE': 'django.db.backends.oracle',
        # 'NAME': 'xe',
        # 'USER': 'ora_pro',
        # 'PASSWORD': '1234',
        # 'HOST': 'localhost',
        # 'PORT': '1521',
        
        # #oracle cloud for windows 
        # 'ENGINE': 'django.db.backends.oracle',
        # 'NAME': 'dbseoul_high',
        # 'USER': 'ADMIN',
        # 'PASSWORD': 'Epdlxjqpdltm1!',

        #oracle cloud for windows 
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'db01_high',
        'USER': 'ADMIN',
        'PASSWORD': 'Epdlxjqpdltm1!',

    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')



# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
