# Generated by Django 4.0.5 on 2022-06-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BourgeoisMember',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('PW', models.CharField(max_length=100)),
                ('NAME', models.CharField(max_length=100)),
                ('AGE', models.IntegerField(default=0)),
                ('GENDER', models.CharField(max_length=16)),
                ('LEGION', models.CharField(max_length=50)),
                ('CuriousLEGION', models.CharField(max_length=50)),
                ('CuriousSECTOR', models.CharField(max_length=50)),
            ],
        ),
    ]
